language: generic

# Dependency of the minted package and install fonts
# Use optipng and imagemagick so we can get a thumbnail of our cv
# Also need to fix imagemagick permissions https://stackoverflow.com/a/52853157
before_install:
  - sudo apt-get install python-pygments
  - sudo apt-get install optipng
  - sudo apt-get install ghostscript
  - sudo apt-get install imagemagick
  - sudo sed -i '/PDF/s/none/read|write/' /etc/ImageMagick-6/policy.xml
  - mkdir $HOME/.fonts
  - cp -a $TRAVIS_BUILD_DIR/src/fonts/. $HOME/.fonts/
  - fc-cache -f -v

install:
  - source ./texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

# Change working directory so including files will work
before_script: cd $TRAVIS_BUILD_DIR/src/

script:
  # Texliveonfly will download packages automatically
  - texliveonfly --compiler=xelatex cv.tex
  # Build CV
  - latexmk --pdf -pdflatex="xelatex --shell-escape" cv.tex

  # Create thumbnail of first page of cv
  - convert cv.pdf[0] -resize 800x800 -flatten cv_thumbnail.png
  - convert cv_thumbnail.png -shave 1x1 -bordercolor black -border 1 cv_thumbnail.png
  - convert cv_thumbnail.png -bordercolor None -border 20x20 \( +clone -background black -shadow 50x5+5+5 \) -compose DstOver -composite -compose Over cv_thumbnail.png
  - optipng cv_thumbnail.png

notifications:
  email: false

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: h9DO0sI15qF56nLEbrVZdKqhV46Wpkz3Km35Z9i9Ey1i+rIvYky4uE/JCI77VZgcBsk5atm391na/dguUfuMbZ1T16Swgsp1x/SByN8+TqMoSyuz+r4FQAecS27kZPnDpT6yL+ICl1uKIW1ijWFXmmrVgTyzHAHTe0Z8mLXwaqRClcF+VzgIFh+/aTlYuua+7cUPNRZvHZSHRHMgjxcDxZ1O7M1AafqTH9+9IbcPCaF2ebkevyJinCFBp+ZAT7N0ilfpIfwiYlhY09OGVduLMstMGyZBhMH+U2kFHGjdbVxvEyLCSEP7jqknhhHKFJBxjAh1hILXfIj4iMMHEGMJ6w21+A5xteKMF8+PvL3aRlSI45ENSLPPYufD9xl/x1nKq73+sjI0QW3uYBEmMR+4QgSwlT76fUznJHohI29XhtrPSC+/gjlZyy94OW1MKPWGECmtXXoD5v1+8u21Imf53XKawNF+nLAK8jRTVfsIi007Ce7Mshg4lScTpFfUDMDv2YBqBz2lm2Zl7KBpSDCEaWWNC+LnnHThgRLkCPi82i4+53tZfoiysO9pTT2GAqiiQGeKmJQ+/ngtLd83k5xUGueMBE7loo3iCrbrdP7VN/17/Ypgi4S0g26AYmF2KMGdOLj3gg83S/DK7fRlnM6kD14SYbpGVcnByYjGQ3j04No=
  file: 
    - "./cv.pdf"
    - "./cv_thumbnail.png"
  on:
    repo: chrisleaman/cv
    tags: true
