language: generic

# Dependency of the minted package and install fonts
# Use optipng and imagemagick so we can get a thumbnail of our cv
# Also need to fix imagemagick permissions https://stackoverflow.com/a/52853157
before_install:
  - sudo apt-get install python-pygments
  - sudo apt-get install optipng
  - sudo apt-get install ghostscript
  - sudo apt-get install imagemagick
  - sudo sed -i '/PDF/s/none/read|write/' /etc/ImageMagick-6/policy.xml
  - mkdir $HOME/.fonts
  - cp -a $TRAVIS_BUILD_DIR/src/fonts/. $HOME/.fonts/
  - fc-cache -f -v

install:
  - source ./texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

# Change working directory so including files will work
before_script: cd $TRAVIS_BUILD_DIR/src/

script:
  # Texliveonfly will download packages automatically
  - texliveonfly --compiler=xelatex cv.tex
  # Build CV
  - latexmk --pdf -pdflatex="xelatex --shell-escape" cv.tex

  # Create thumbnail of first page of cv
  - convert cv.pdf[0] -resize 800x800 -flatten cv_thumbnail.png
  - convert cv_thumbnail.png -shave 1x1 -bordercolor black -border 1 cv_thumbnail.png
  - convert cv_thumbnail.png -bordercolor None -border 20x20 \( +clone -background black -shadow 50x5+5+5 \) -compose DstOver -composite -compose Over cv_thumbnail.png
  - optipng cv_thumbnail.png

notifications:
  email: false

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: dSBYm+3IhohaTyQR4RThvAxBnQZVY7YkIkVR0/BaENbPuBYIHxW26Nc/HCQZiZhQ04ZRPAjlPZrs8jre0FK4GjJW787SfN8R/wtYMbvhvOv7xbWUKOgl85hgeRledeJGmLP03/RPQ5bjcJf1WF62sdXiqhb4m08l9HBpcNmu+GSlY7IDZic87QWGTcU84TsB6LRNklG1p8guzTrtfLKq9L4Woyi5rvdwF76SeVXbOg3zTYfHrVrSLGqZMHjfwV/+ZK486x9M7SILVvlsf5p8lepM5uiP8cqTTyHLAwCb/eBcZaIyy3afagOQ1nIw4S7yV5VccMTvUTMFmZ/lP8+nfetXmbUOzJ2gwDYmrO56kQUkzrnTsLblRcoDCJK3baT5H3hJKOTjt1Vga+oZu9k+dd2qEBSCKDtY2XdRzDnbJnWzWJHs9OQqxkheLbusrdWr7yFRZ8Fff/iLRjx6L0of0AZmqFo62i9piVZ1luQnKfuqWpaBvS0B9RpLdpL3HnKVSiK5EGbbsLSMQB0krZ/QWNZrry/tR+BgyfHzPE1xKQ3MR5js6cybzGNryyQRmjl/6WK/udRw+pEpzFrN1lxU/rUeuE7ZMP82majoPlGi197p8HaYeh4llVD1tbu1Kw2rxhohodSqseBr2Lh/KTFZwB3mHfDSGIUa4UR2pot4owg=
  file: 
    - "./cv.pdf"
    - "./cv_thumbnail.png"
  on:
    repo: chrisleaman/cv
    tags: true
