on: 
  push:
    tags:
    - '*'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make imagemagick optipng
            make
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "src/cv.pdf, cv_thumbnail.png"
